export const KEY_USER = "@USER";
export const KEY_TOKEN = "@TOKEN";
export const KEY_REFRESH_TOKEN = "@REFRESH_TOKEN";
export const KEY_SIGNED = "@SIGNED";
export const KEY_SIDEBAR = "@SIDEBAR";
export const KEY_DAILY_OPTIONS = "@DAILY_OPTIONS";
export const KEY_PACKAGE_OPTIONS = "@PACKAGE_OPTIONS";
export const KEY_DISCIPLINE_OPTIONS = "@DISCIPLINE_OPTIONS";
export const KEY_CONSTRUCTION_OPTIONS = "@CONSTRUCTION_OPTIONS";

export const KEY_DASHBOARD_PACKAGE_OPTIONS = "@DASHBOARD_PACKAGE_OPTIONS";
export const KEY_DASHBOARD_CONSTRUCTION_OPTIONS =
  "@DASHBOARD_CONSTRUCTION_OPTIONS";
export const KEY_DASHBOARD_MEASUREMENT_OPTIONS =
  "@DASHBOARD_MEASUREMENT_OPTIONS";
export const KEY_DASHBOARD_CHECKLIST_OPTIONS = "@DASHBOARD_CHECKLIST_OPTIONS";
export const KEY_DASHBOARD_EMPLOYEE_OPTIONS = "@DASHBOARD_EMPLOYEE_OPTIONS";
export const KEY_DASHBOARD_USER_OPTIONS = "@DASHBOARD_USER_OPTIONS";
